name: Kong Configuration

on:
  push:
    branches:
      - main

    paths:
      - "code/dev/config/kong.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DECK_KONG_ADDR: ${{ secrets.DECK_KONG_ADDR }}
      DECK_KONG_KEY_AUTH: ${{ secrets.DECK_KONG_KEY_AUTH }}
      DECK_LOG_URL: ${{ secrets.DECK_LOG_URL }}
      DECK_LOG_SECRET_TOKEN: ${{ secrets.DECK_LOG_SECRET_TOKEN }}

    defaults:
      run:
        working-directory: ./code/dev/config

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup decK
        uses: kong/setup-deck@v1
        with:
          deck-version: "1.55.0"

      - name: Validate Kong Config
        run: deck gateway validate kong.yaml --headers "apikey:${{ secrets.DECK_KONG_KEY_AUTH }}"

      - name: Preview Changes (Diff)
        run: |
          deck gateway diff kong.yaml --headers "apikey:${{ secrets.DECK_KONG_KEY_AUTH }}"

      - name: Apply Changes (Sync)
        run: |
          deck gateway sync kong.yaml --headers "apikey:${{ secrets.DECK_KONG_KEY_AUTH }}"
